<div class="text-center">
	<h1 class="text-green">Work Order Management</h1>
	<h1 class="text-blue">Dobrodošli na administratorski deo!</h1>
</div>
<?php if ($this->postojeUpitiZaIzvrsenje): ?>
<br /><br />
<div class="text-center">
	<h1 ><a href="<?php echo URL_PREFIX;?>/dbupdate/execute" class="text-red">POTREBNO JE AŽURIRATI BAZU</a></h1>
</div>
<?php endif;?>


<div class="text-center">
	<img style="border: 0;" src="<?php echo $this->baseUrl();?>/dist/img/admin_icon.png">
</div>
