<?php include_once APPLICATION_PATH . "/configs/Constants.php";?>
<script type="text/javascript">
 $(document).ready(function(){
 	$('#novi').click(function(event){
 		event.preventDefault();
		location.href = '<?php echo URL_PREFIX.Constants::$korisnickaAdministracijaPrikazPutanja;?>';
 	});
 	
 });
</script>
<?php $redniBroj = 0;?>
	<section class="invoice">
		<div class="row">
        	<div class="col-xs-12">
          		<h2 class="page-header">
            		KORISNICKA PODRSKA          
          		</h2>
        	</div>
      	</div>
		<!--  <div class="row">
			<div class="box-body no-padding">
				<table class="table table-condensed">
					<tr>
						<th style="width: 10px">#</th>
						<th>Naziv</th>
						<th style="width: 80px">Promena/Brisanje</th>
					</tr>
<?php foreach ($this->korisnici as $korisnik):?>
                	<tr>
						<td><?php echo ++$redniBroj . ".";?></td>
						<td><?php echo $korisnik['username'];?></td>
						<td>
							<div>
								<a href="<?php echo URL_PREFIX;?>/administracija/operativni-sistem-unos?id=<?php echo $operativniSistem['id']; ?>"
									class="btn btn-xs btn-teal tooltips">	
									<i class="fa fa-pencil-square-o text-blue"></i>
								</a>
								&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
								<a  href="#"
									data-href="<?php echo URL_PREFIX;?>/administracija/operativni-sistem-brisanje?id=<?php echo $operativniSistem['id']; ?>"
									data-toggle="modal"
									data-target="#confirm-delete">								
									<i class="fa fa-minus-square-o text-red"></i>
								</a>
							</div>
						
					</td>
					</tr>
<?php endforeach;?>
                </table>
			</div>
		</div>-->
		<hr>
		<div class="row no-print">
        	<div class="col-xs-12">
          		<a href="<?php echo Constants::$dodajKorisnikaPutanja?>" id="novi" class="btn btn-success pull-right"><i class="fa fa-plus"></i> Dodaj korisnicku podrsku</a>
          	</div>
      	</div>	
	</section>
	
<div class="modal modal-danger fade" id="confirm-delete">

   	<div class="modal-dialog">
   	
       	<div class="modal-content">
       	
           	<div class="modal-header">
               	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
              		<span aria-hidden="true">&times;</span>
               	</button>
               	<h4 class="modal-title">Brisanje unete korisnicke podrske</h4>
           	</div>
           	
           	<div class="modal-body">
               	<p>Uneta korisnicka podrska ce biti obrisana</p>
            </div>
           	
           	<div class="modal-footer">
              	<button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Odustani</button>
               	<a href="<?php echo URL_PREFIX;?>/administracija/operativni-sistem-brisanje?id=<?php echo $operativniSistem['id']; ?>" class="btn btn-outline">&times;&nbsp;&nbsp;Obriši</a>
           	</div>
           	
        </div>
        
	</div>
	
</div>

