<div>
	<br />
	<br />
	<div style="padding: 10px;">
		<h1 style="padding-bottom:10px;">Dopuna baze podataka</h1>
		<?php foreach ($this->dbUpdate as $query):?>
		<p>Redni broj upita: <?php echo $query['id']; ?></p>
		<p>Opis: <?php echo $query['opis']; ?></p>
		<p>Poruka: <?php if($this->poruke[$query['id']]==1){ ?>
				<span style="color:green">Upit je USPEŠNO izvršen!</span>
			   <?php }else{ ?> 
			   <?php echo $this->poruke[$query['id']];?>
			   <?php };?>
	</p>
	<hr />
	<?php endforeach;?>
</div>
</div>