<script type="text/javascript">
 $(document).ready(function(){
 	<?php if($this->message):?>
		$("#poruka").show().delay(5000).fadeOut();
    <?php endif;?>
 	
 });
</script>
<?php $redniBroj = 0;?>
	<section class="invoice">
	<div class="row" id="poruka" style="display:none;">
		<div class="col-sm-1"></div>
		<div class="col-md-10">
			<div class="alert alert-<?php echo $this->messageType;?>"><?php echo $this->message;?></div>
		</div>
</div>
		<div class="row">
        	<div class="col-xs-12">
          		<h2 class="page-header">
            		OPERATIVNI SISTEMI           
          		</h2>
        	</div>
      	</div>
		<div class="row">
			<div class="box-body no-padding">
				<table class="table table-condensed">
					<tr>
						<th style="width: 10px">#</th>
						<th>Naziv</th>
						<th style="width: 80px">Promena/Brisanje</th>
					</tr>
<?php foreach ($this->operativniSistemi as $operativniSistem):?>
                	<tr>
						<td><?php echo ++$redniBroj . ".";?></td>
						<td><?php echo $operativniSistem['naziv'];?></td>
						<td>
							<div>
								<a href="<?php echo URL_PREFIX;?>/administracija/operativni-sistem-unos?id=<?php echo $operativniSistem['id']; ?>"
									class="btn btn-xs btn-teal tooltips">	
									<i class="fa fa-pencil-square-o text-blue"></i>
								</a>
								&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
								<a  href="<?php echo URL_PREFIX;?>/administracija/operativni-sistem-brisanje?id=<?php echo $operativniSistem['id']; ?>">								
									<i class="fa fa-minus-square-o text-red"></i>
								</a>
							</div>
						
					</td>
					</tr>
<?php endforeach;?>
                </table>
			</div>
		</div>
		<hr>
		<div class="row no-print">
        	<div class="col-xs-12">
          		<a href="/administracija/operativni-sistem-unos" id="novi" class="btn btn-success pull-right"><i class="fa fa-plus"></i> Dodaj novi</a>
          	</div>
      	</div>	
	</section>
	


