<section class="invoice">
	<div class="box box-info">
    	<div class="box-header with-border">
        	<h3 class="box-title">Unos novog operativnog sistema</h3>
        </div>
        <form class="form-horizontal">
        	<div class="box-body">
            	<div class="form-group">
                	<label for="unesiNazivOS" class="col-sm-2 control-label">Naziv operativnog sistema</label>
					<div class="col-sm-10">
                    	<input type="text" class="form-control" id="unesiNazivOS" placeholder="Naziv...">
                  	</div>
                </div>                
            </div>
            <div class="box-footer">
                <a href="/administracija/operativni-sistem-prikaz" class="btn btn-default">Odustani</a>
                <button type="submit" class="btn btn-info pull-right">Sačuvaj</button>
        	</div>
    	</form>
	</div>
</section>