<script type="text/javascript">
 $(document).ready(function(){
 	$('#novi').click(function(event){
 		event.preventDefault();
		location.href = '<?php echo URL_PREFIX;?>/administracija/tip-racunara-unos';
 	});
 	
 });
</script>
<?php $redniBroj = 0;?>
	<section class="invoice">
		<div class="row">
        	<div class="col-xs-12">
          		<h2 class="page-header">
            		Tipovi racunara           
          		</h2>
        	</div>
      	</div>
		<div class="row">
			<div class="box-body no-padding">
				<table class="table table-condensed">
					<tr>
						<th style="width: 10px">#</th>
						<th>Naziv</th>
						<th style="width: 80px">Promena/Brisanje</th>
					</tr>
<?php foreach ($this->tipoviRacunara as $tipRacunara):?>
                	<tr>
						<td><?php echo ++$redniBroj . ".";?></td>
						<td><?php echo $tipRacunara['naziv'];?></td>
						<td>
							<div>
								<a href="<?php echo URL_PREFIX;?>/administracija/tip-racunara-unos?id=<?php echo $tipRacunara['id']; ?>"
									class="btn btn-xs btn-teal tooltips">	
									<i class="fa fa-pencil-square-o text-blue"></i>
								</a>
								&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
								<a  href="<?php echo URL_PREFIX;?>/administracija/tip-racunara-brisanje?id=<?php echo $tipRacunara['id']; ?>">								
									<i class="fa fa-minus-square-o text-red"></i>
								</a>
							</div>
						
					</td>
					</tr>
<?php endforeach;?>
                </table>
			</div>
		</div>
		<hr>
		<div class="row no-print">
        	<div class="col-xs-12">
          		<a href="/administracija/tip-racunara-unos" id="novi" class="btn btn-success pull-right"><i class="fa fa-plus"></i> Dodaj novi</a>
          	</div>
      	</div>	
	</section>