<script type="text/javascript">
 $(document).ready(function(){
 	$('#novi').click(function(event){
 		event.preventDefault();
		location.href = '<?php echo URL_PREFIX;?>/administracija/radni-nalog-unos';
 	});
 	
 });
</script>

<?php $redniBroj = 0;?>
<section class="invoice">
	<div class="row">
		<div class="col-xs-12">
			<h2 class="page-header">RADNI NALOZI</h2>
		</div>
	</div>

	<form class="form-horizontal" name="frmRadniNaloziPrikaz"
		id="frmFilterZaNaloge"
		action="<?php echo Constants::$radniNalogPrikazPutanja;?>"
		method="get">
    	<?php echo $this->form->id;?>
    	<div class="box-body">

			<div class="form-group">
				<label for="username" class="col-sm-2 control-label">Radnik: </label>
				<div class="col-sm-2">
                    <?php echo $this->form->username; ?>
            	</div>
			</div>

			<div class="form-group">
				<label for="racunar" class="col-sm-2 control-label">Racunar: </label>
				<div class="col-sm-2">
                    <?php echo $this->form->racunar; ?>
            	</div>
			</div>

			<div class="form-group">
				<label for="kvar" class="col-sm-2 control-label">Tip kvara: </label>
				<div class="col-sm-2">
                    <?php echo $this->form->kvar; ?>
            	</div>
			</div>

			<div class="form-group">
				<label for="odDatuma" class="col-sm-2 control-label">Od datuma: </label><!-- Pisi datum u formatu yyyy-mm-dd -->
				<div class="col-sm-2">
                    <?php echo $this->form->odDatuma; ?>
            	</div>
			</div>

			<div class="form-group">
				<label for="doDatuma" class="col-sm-2 control-label">Do datuma: </label><!-- Pisi datum u formatu yyyy-mm-dd -->
				<div class="col-sm-2">
                    <?php echo $this->form->doDatuma; ?>
            	</div>
			</div>

			<div class="form-group">
				<label for="status" class="col-sm-2 control-label">Status: </label>
				<div class="col-sm-2">
                    <?php echo $this->form->status; ?>
            	</div>
			</div>
			
			<div class="form-group">
				<label for="opis" class="col-sm-2 control-label">Opis: </label>
				<div class="col-sm-2">
                    <?php echo $this->form->opis; ?>
            	</div>
			</div>
			
			<!-- /.box-body -->
			<div class="box-footer">
    				<?php  echo $this->form->trazi; ?>
    				<?php  echo $this->form->generisi; ?>
              </div>
             <!-- /.box-footer -->
		</div>
	</form>


	<div class="row">
		<div class="box-body no-padding">
				
			<table class="table table-condensed">
				<tr>
					<th style="width: 10px">#</th>
					<th>Id</th>
					<th>Radnik</th>
					<th>Racunar</th>
					<th>Kvar</th>
					<th>Datum kreiranja</th>
					<th>Status</th>
					<th>Opis kvara</th> 
					<th>Datum zavrsetka</th>
					<th style="width: 80px">Promena/Brisanje</th>
				</tr>
<?php foreach ($this->radniNalozi as $radniNalog):?>
                	<tr>
					<td><?php echo ++$redniBroj . ".";?></td>
					<td><?php echo $radniNalog['id'];?></td>
					<td><?php echo $radniNalog['username'];?></td>
					<td><?php echo $radniNalog['naziv'];?></td>
					<td><?php echo $radniNalog['kvar'];?></td>
					<td><?php echo $radniNalog['vreme_kreiranja'];?></td>
					<td><?php echo $radniNalog['status'];?></td>
					<td><?php echo $radniNalog['opis_kvara'];?></td>
					<td><?php echo $radniNalog['vreme_zavrsetka'];?></td>
					<td>
							<div>
								<a href="<?php echo URL_PREFIX;?>/radniNalog/radni-nalog-update?id=<?php echo $radniNalog['id']; ?>"
									class="btn btn-xs btn-teal tooltips">	
									<i class="fa fa-pencil-square-o text-blue"></i>
								</a>
								&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
								<a  href="<?php echo URL_PREFIX;?>/radniNalog/radni-nalog-brisanje?id=<?php echo $radniNalog['id']; ?>">								
									<i class="fa fa-minus-square-o text-red"></i>
								</a>
							</div>
						
					</td>
				</tr>
<?php endforeach;?>
                </table>
		</div>
	</div>
	<hr>
</section>
	
<div class="row">			
    <div class="col-md-12 text-right">
		<?php echo $this->paginationControl($this->radniNalozi, 'Sliding', 'pagination/my_pagination_control.phtml');?>
    </div>
</div>



